openapi: 3.1.0
info:
  version: 1.0.0
  title: formation-API.com
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Employee
    description: Example Employee operations.
  - name: Salary
    description: Operations about salary.
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  '/employees':
    $ref: 'paths/employees.yaml'
  '/employee/{id}':
    $ref: 'paths/employees_{id}.yaml'
  '/new-employee':
    $ref: 'paths/new-employee.yaml'
  '/update-strength/{id}':
    $ref: 'paths/update-strength_{id}.yaml'
  '/update-weakness/{id}':
    $ref: 'paths/update-weakness_{id}.yaml'
  '/raise-salary/{employee-id}/{salary-id}':
    $ref: 'paths/raise-salary_{employee-id}_{salary-id}.yaml'

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
